version: "3.4"

volumes:
  db-data:
  rabbitmq-data:

services:
  nginx:
    restart: always
    image: nginx
    container_name: django.nginx
    ports:
      - 8000:8000
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./backend/static:/static
    depends_on:
      - django

  postgresql:
    build:
      context: ./db
    container_name: django.postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "mysite"
      POSTGRES_USER: "mysiteuser"
      POSTGRES_PASSWORD: "mysitepass"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: django.adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgresql

  django:
    restart: always
    build:
      context: ./backend
    image: django-main
    container_name: django.django
    volumes:
      - ./backend:/app
    expose:
      - "8001"
    depends_on:
      - postgresql
      - rabbitmq
    command: bash -c "uwsgi --socket :8001 --module mysite.wsgi"

  rabbitmq:
    container_name: django.rabbitmq
    image: rabbitmq:latest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
      - 5672:5672

  celery:
    image: django-main
    container_name: django.celery
    volumes:
      - ./backend:/app
    environment:
      DB_HOST: "postgresql"
      DB_NAME: "mysite"
      DB_USER: "mysiteuser"
      DB_PASS: "mysitepass"
    depends_on:
      - django
    command: bash -c "celery -A mysite worker -l info"

  celery-beat:
    image: django-main
    container_name: django.celery-beat
    volumes:
      - ./backend:/app
    environment:
      DB_HOST: "postgresql"
      DB_NAME: "mysite"
      DB_USER: "mysiteuser"
      DB_PASS: "mysitepass"
    depends_on:
      - django
    command: bash -c "celery -A mysite beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler --pidfile="

  selenium:
    image: selenium/standalone-chrome-debug:3.141.59
    container_name: 'django.selenium'
    ports:
      - 4445:4444
      - 5901:5900
